In [1]:
import numpy as np

In [4]:
# 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
arr=np.array([i if i < 3 or i > 6 else -i for i in range(1,12)])
print(arr)

arr=np.array(range(1,12))
arr[2:6]*=-1
print(arr)


[ 1  2 -3 -4 -5 -6  7  8  9 10 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


In [5]:
# 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
a = np.random.rand(3, 6)

print(a)
print(a[a>0.5].size)

[[0.91560015 0.60776537 0.17466729 0.29837217 0.05158748 0.3724119 ]
 [0.19446284 0.01698029 0.37839466 0.56787024 0.93894064 0.41918664]
 [0.39954375 0.90057334 0.78346188 0.9125745  0.93987263 0.66322739]]
9
