In [1]:
import numpy as np

In [2]:
# [簡答題] 請問下列這三種方法有什麼不同？
# a.sum() 
# np.sum(a)
# sum(a) 

# '''Answer
# a.sum()只適用於a為陣列，可求得所有元素的總和
# np.sum(a)適用於a為列表或陣列，可求得所有元素的總和
# sum(a)適用於a為一維的列表或任何維度的陣列，或當a為二維以上的陣列時則會降維
# '''

In [3]:
# 請對一個 5x5 的隨機矩陣作正規化的操作。
A = np.random.random((5, 5))
B = A.copy()
B = (B-B.min())/(B.max()-B.min())
print(A,B,sep='\n')

[[0.45464728 0.60846542 0.32752332 0.6589505  0.46532913]
 [0.21963632 0.8864056  0.44321038 0.17361214 0.2491218 ]
 [0.05969069 0.53412965 0.12663483 0.42216626 0.14785484]
 [0.11814753 0.43834875 0.74517463 0.00812488 0.17324579]
 [0.35047567 0.79210779 0.19867087 0.56076701 0.53340613]]
[[0.5084051  0.68354061 0.36366327 0.74102232 0.52056733]
 [0.24082441 1.         0.49538318 0.18842183 0.27439623]
 [0.05871222 0.59890278 0.13493402 0.4714226  0.15909487]
 [0.12527048 0.48984779 0.83919609 0.         0.1880047 ]
 [0.38979655 0.89263363 0.2169534  0.62923177 0.598079  ]]


In [4]:
# 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。
arr = np.random.default_rng().integers(1,100,size=(10))
arr2 = arr.copy()
arr2[arr2.argmax()]=-1
print(arr,arr2,sep='\n')

[39 15 56 27 43  2 48 36 59 95]
[39 15 56 27 43  2 48 36 59 -1]
