In [1]:
import numpy as np

In [2]:
# [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

# '''Answer
# np.zeros()可以依照傳入的引數來建立特定大小且全為0的陣列。
# np.empty()則是依照傳入的引數來建立特定大小且元素未初始化的陣列。

# '''

In [3]:
# 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
a = np.random.rand(2, 3)*100
a2=a.copy().round()

print(a)
print(a2)

[[38.16003947 33.24083581 43.75953977]
 [50.49621189 28.8080644  47.01246178]]
[[38. 33. 44.]
 [50. 29. 47.]]


In [4]:
# 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。
m = 20
n = 40

from numpy.random import default_rng
integers = default_rng().integers(m, n, size=(2,3))
print(integers)

# 在不用「整數亂數方法」的限制下

a = np.random.rand(2, 3)
print((a * (n - m)).round() + m)


[[28 21 30]
 [36 24 26]]
[[21. 21. 36.]
 [30. 30. 38.]]
