In [1]:
import numpy as np

In [2]:
# [簡答題] 請問下列程式碼，運算結果分別為何？
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

# '''Answer
# a + a => [40,60,80,100]
# a + b => [21,32,43,54]
# a + c => [21,31,41,51]
# a + d => [21,31,41,51]
# a + e => size 1x2 與 1x4 無法相加
# '''

In [3]:
# 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
A = np.ones(3)*1
B = np.ones(3)*2

# 不用迴圈
print((A+B)*(-A/2))

# 用迴圈
print(np.array([(A[i]+B[i])*(-A[i]/2) for i in range(A.size)]))
    


[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


In [4]:
# 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

A = np.ones((1,6))
B = np.ones((6,1))
print(A @ B)
print(A * B)

[[6.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
